### ISSUE TITLE
Optimizar rendimiento sobre PostgreSQL

### ISSUE THREAD

**Issue by ChristopherCastro** [ChristopherCastro/gencon#3]
Optimizar las consultas de la aplicación para el motor de base de datos PostgreSQL para poder realizar la migración desde MySQL a PostgreSQL.

### Tareas a realizar

- [x] Reducir en lo posible el uso de JOINS
- [x] Y también el uso de sub-consultas en clausulas WHERE
- [x] Verificar que todo sigue funcionando correctamente (casos de pruebas)

**Comment by carolbarce** [comment]
Se ha revisado el codigo de las vistas y paquetes con más carga.
Se han substituido ciertas estructuras, creado índices y con ello eliminado los joins más pesados.
Obtenido una mejora del rendimiento del 30%

El informe detallado pertinente está en repositorio del area de sistemas.
