### ISSUE TITLE
Carrito de compra

### ISSUE THREAD

**Issue by ChristopherCastro** [ChristopherCastro/gencon#5]
Una vez añadido un producto al carrito de compra ya no se puede quitar/eliminar del mismo. El botón destinado a dicha tarea no parece funciona, simplemente refresca la interfaz pero sin cambios aparentes.

### Tareas a realizar

- [x] Revisar la interfaz y asegurar de que el botón opera con normalidad
- [x] Revisar la lógica relacionada al carrito

**Comment by carolbarce** [comment]
Listo!
Interfaz cambiada y probado el botón.
Falta relacionar con la nueva versión del fichero "gestionCarrito.java" con commit a fecha de 7/12/2015 a las 13:34
